// src/config-schema.ts — what site.config.ts may contain. Template-owned.
//
// You do not edit this file. Your values live in site.config.ts at the root of
// the repository; this file only describes them, so the type-check can tell you
// when a value is missing or misspelled. When you sync a newer template, this
// file is replaced and your site.config.ts is left alone. A new setting arrives
// here as optional, so your existing values keep working until you choose to
// set it.

export interface SiteConfig {
  /**
   * The base URL of your records vault's `published` branch — where the vault's
   * publish workflow serves corpus-latest.json, standing.json, feed.xml, and
   * receipts/. Use EITHER:
   *   • the records repo's Pages URL:
   *       https://<org>.github.io/<org>-records/
   *   • or the raw branch URL:
   *       https://raw.githubusercontent.com/<org>/<org>-records/published/
   * A trailing slash is fine either way. This is the only link between the two
   * repositories; the site reads these files and never touches the vault itself.
   */
  publishedBaseUrl: string;

  /** Your organization's name, shown in the header and the page titles. */
  orgName: string;

  /** How a reader reaches you — an email address or a URL. Shown in the footer. */
  contact: string;

  /** Your accent colour as a hex value (e.g. "#2f6f4f"). Used for links and the header rule. */
  accent: string;

  /**
   * Where this site is served, for canonical URLs. For GitHub Pages this is your
   * org's Pages origin, e.g. "https://<org>.github.io". Optional.
   */
  site?: string;

  /**
   * The path this site is served under. On GitHub Pages a project site lives at
   * /<org>-site/, so set base to "/<org>-site". A user/organization site at the
   * domain root uses "/". Defaults to "/".
   */
  base?: string;

  /**
   * The Ask box's address: the Function URL your Ask function's deploy printed
   * (it ends in ".lambda-url.<region>.on.aws/"). Leave it empty, or leave it out,
   * and the site has no Ask box at all — every page still works, and nothing else
   * changes.
   */
  askUrl?: string;

  /**
   * The line shown under the Ask box. Copy the `disclaimer` from your rules
   * repo's policy.yaml so the box and its rules say the same thing; the site
   * never reads the rules repo itself. Only shown when askUrl is set.
   */
  askDisclaimer?: string;
}
